name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: kas-latest
    env:
      DL_DIR: ${{ secrets.DL_DIR }}
      TMPDIR: ${{ secrets.TMPDIR }}
      SSTATE_DIR: ${{ secrets.SSTATE_DIR }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Pip Installer
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            kas

      - name: Building poky image for rpi
        run: |
          kas build kas-poky-rpi.yml

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            build/conf
            ${{env.TMPDIR}}/deploy/images/**/homebridge-image-raspberrypi3.rpi-sdimg
