name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: kasproject/kas:latest
      options: --user 1001

    steps:
      - uses: actions/checkout@v2

      - name: Building poky image for rpi
        run: |
          kas build kas-poky.yml:board-rpi.yml
